export const SET_LOADING = 'SET_LOADING'
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const SET_USER_DATA = 'SET_USER_DATA'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const SET_TASKS = 'SET_TASKS'
export const SET_PAGE = 'SET_PAGE'
